name: Backend CI/CD

on:
  pull_request:

jobs:
  pre_job:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      # save me my credits
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          # All of these options are optional, so you can remove them if you are happy with the defaults
          concurrent_skipping: "same_content"
          skip_after_successful_duplicate: "true"
          paths_ignore: '["**/README.md"]'
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: pip install pylint
      - name: Run pylint
        run: pylint ./Backend
        # TODO: 8.0 is the minimum score for a passing lint use: --fail-under=8.0

  pytest:
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - uses: actions/cache@v2
        id: poetry-cache
        with:
          path: |
            ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-
      - name: Install deps
        run: |
          pip install -U pip
          pip install poetry==1.4.2
          poetry install
        env:
          POETRY_VIRTUALENVS_CREATE: false
      - name: Setup GIT
        run: |
          git config --global user.name "css4442_testing"
          git config --global user.email "css4442_testing@pytest.python"
      - name: Run tests
        run: poetry run pytest -vv --exitfirst -n auto
# TODO: Add coverage
