name: Frontend CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

defaults:
  run:
    working-directory: ./Frontend/

jobs:
  pre_job:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      # save me my credits
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          concurrent_skipping: "same_content"
          skip_after_successful_duplicate: "true"
          paths_ignore: '["**/README.md"]'

      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

  lint:
    needs: pre_job
    runs-on: ubuntu-latest

    steps:
      - name: Lint
        run: npm run lint

  build:
    needs: pre_job
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: npm run build

      - name: Run unit tests
        run: npm run test:unit

      - name: Run Playwright tests
        run: npm run test
